### ISSUE TITLE
AoCF support

### ISSUE THREAD

**Issue by brliron** [thpatch/thcrap#75]
List of issues that needs to be solved for full AoCF support

- [ ] #70 Subtitles patching
- [ ] #71 Move and resize balloons
- [ ] #72 Skipgame patch
- [ ] #73 Missing translations in config screen
- [ ] #74 Left-align the menu settings

**Comment by brliron** [comment]
Projects are better suited for this - moved to https://github.com/thpatch/thcrap/projects/2
